name: lightReports
author: lightStudios
version: 0.1.0
main: io.lightplugins.reports.Light
api-version: 1.21
depend: []
softdepend: [ ]
loadbefore: [ ]
libraries: [ ]
#  - org.mariadb.jdbc:mariadb-java-client:2.7.4
#  - com.zaxxer:HikariCP:5.1.0
commands:
  report:
    description: The root command for the Report module
    aliases: [r, rep]