# Here you can change the language of this module.
# Currently, the following languages are available:
#
#  'en' -> English translations.
#  'de' -> German translations.
module-language: en
# The report cooldown in seconds to prevent report spamming.
report-cooldown: 5
# The reason types that can be used for reports.
report-reasons:
  - 'Hacking'
  - 'Chatverhalten'
  - 'Trolling'